[template]
  incoming-hooks = ["Sanity"]

[template.environment]
  NEXT_PUBLIC_SANITY_PROJECT_ID="106s9cznd"
  NEXT_PUBLIC_SANITY_DATASET="production"
  SANITY_API_WRITE_TOKEN="skC9kZuNfomFEGwDL39uFaj5UxeMq9VGNpoNGOXmEQEnG6A8sIRRSGuIEKfLxnkbOcDfPwQMYX74RBqgPbdl4Ut1UGYUa5vPLpLocZD4bThfr3SbaGKOtM4btVszsdY0E56Ul2RL7yJv2bGlOM5M7erAKvoRntxJLbWP3oDrooTFWL3wyeV2"
  SANITY_API_READ_TOKEN="skC9kZuNfomFEGwDL39uFaj5UxeMq9VGNpoNGOXmEQEnG6A8sIRRSGuIEKfLxnkbOcDfPwQMYX74RBqgPbdl4Ut1UGYUa5vPLpLocZD4bThfr3SbaGKOtM4btVszsdY0E56Ul2RL7yJv2bGlOM5M7erAKvoRntxJLbWP3oDrooTFWL3wyeV2"
